### ISSUE TITLE
[PE-D][Tester A] Undo command has wrong message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-W17-3/tp#135] opened 2023-03-31 18:21 UTC
When I undo an `add` command, the message says `Retrieved most recent deleted event: Empty string for Undo action now`, when it should say that the added event has been removed.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: glozxi/ped#4

**Comment by lhy-hoyin** [comment] 2023-04-01 04:28
Duplicate of known bug, see #112 .

**Closed** 2023-04-04 06:25 UTC
Labels: bug, duplicate
